### ISSUE TITLE
Images not getting uploaded and hence result isnt being displayed

### ISSUE THREAD

**Issue by AmoghJ001** [krishnaik06/Deployment-Deep-Learning-Model#3]
Hi! I am a newbie in Flask and hence I am facing an error. The web app works fine until I press the Choose button. When I select an image, nothing happens. Its as good as I havent uploaded any, I can again click on Choose button, just to see the same happening again. Please help!

**Comment by Abduttayyeb** [comment]
> Hi! I am a newbie in Flask and hence I am facing an error. The web app works fine until I press the Choose button. When I select an image, nothing happens. Its as good as I havent uploaded any, I can again click on Choose button, just to see the same happening again. Please help!

@AmoghJ001 , have u added uploads folder in the same directory which has static and templates folder..?

**Comment by AmoghJ001** [comment]
> 
> 
> > Hi! I am a newbie in Flask and hence I am facing an error. The web app works fine until I press the Choose button. When I select an image, nothing happens. Its as good as I havent uploaded any, I can again click on Choose button, just to see the same happening again. Please help!
> 
> @AmoghJ001 , have u added uploads folder in the same directory which has static and templates folder..?

Yes, I crosschecked and they are in the same directory. Actually, since I was clueless about why this was happening, I switched to Streamlit. Anyways, Thanks for the help!
